services:
  - type: web
    name: shreic-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn shreic.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shreic.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        fromDatabase:
          name: shreic-db
          property: connectionString

databases:
  - name: shreic-db
    databaseName: shreic
    user: shreic_user
