# Generated by Django 5.2.4 on 2025-07-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bookreq_chatroom_chatw_notification_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatw',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
